version: '3'
services:
  db:
    build: .
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      LANG: ja_JP.UTF-8
volumes:
  pgdata: